# Generated by Django 5.0.3 on 2025-04-12 10:12

import django.contrib.auth.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('postid', models.CharField(db_column='postID', max_length=255, primary_key=True, serialize=False, verbose_name='Post URL')),
                ('p_date', models.DateTimeField(verbose_name='Thời gian đăng')),
                ('groupurl', models.CharField(blank=True, db_column='groupURL', max_length=255, null=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('district', models.CharField(blank=True, max_length=100, null=True, verbose_name='Quận')),
                ('ward', models.CharField(blank=True, max_length=100, null=True, verbose_name='Phường')),
                ('street_address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Đường/Số nhà')),
                ('price', models.IntegerField(blank=True, null=True, verbose_name='Giá cho thuê (VNĐ)')),
                ('area', models.CharField(blank=True, max_length=50, null=True, verbose_name='Kích thước (m²)')),
                ('amenities', models.TextField(blank=True, null=True, verbose_name='Thông tin tiện ích bổ sung')),
                ('contact_info', models.CharField(blank=True, max_length=255, null=True, verbose_name='Thông tin liên hệ')),
                ('react_num', models.IntegerField(blank=True, null=True, verbose_name='Lượt cảm xúc')),
                ('cmt_num', models.IntegerField(blank=True, null=True, verbose_name='Lượt bình luận')),
            ],
            options={
                'db_table': 'post',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('userid', models.BigAutoField(db_column='userID', primary_key=True, serialize=False, unique=True)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'user',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='UserBookmarkPost',
            fields=[
                ('markid', models.BigAutoField(db_column='markID', primary_key=True, serialize=False)),
                ('postid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.post')),
                ('userid', models.ForeignKey(db_column='userID', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'userbookmarkpost',
            },
        ),
    ]
