# Generated by Django 5.0.3 on 2025-04-12 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='postURL',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Post URL'),
        ),
        migrations.AlterField(
            model_name='post',
            name='postid',
            field=models.BigAutoField(db_column='postID', primary_key=True, serialize=False, verbose_name='Post ID'),
        ),
    ]
