# Generated by Django 5.0.3 on 2025-04-12 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_post_posturl_alter_post_postid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='price',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Giá cho thuê (VNĐ)'),
        ),
    ]
