# Generated by Django 5.0.3 on 2025-02-25 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_user_options_alter_comment_table_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='replyid',
        ),
        migrations.AddField(
            model_name='post',
            name='r_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='reply',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Reply',
        ),
    ]
