# Generated by Django 5.0.3 on 2025-04-12 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_post_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='price',
            field=models.IntegerField(blank=True, null=True, verbose_name='Giá cho thuê (VNĐ)'),
        ),
    ]
