# Generated by Django 5.0.3 on 2025-05-01 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_post_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='cmt_num',
        ),
        migrations.RemoveField(
            model_name='post',
            name='groupurl',
        ),
        migrations.RemoveField(
            model_name='post',
            name='react_num',
        ),
        migrations.AlterField(
            model_name='post',
            name='postid',
            field=models.CharField(db_column='postID', max_length=32, primary_key=True, serialize=False, verbose_name='Post ID'),
        ),
    ]
