# Generated by Django 5.0.3 on 2025-05-01 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_post_cmt_num_remove_post_groupurl_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='postURL',
        ),
    ]
