# Generated by Django 5.0.3 on 2025-05-02 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_post_posturl'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='p_url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='URL bài đăng'),
        ),
    ]
