# Generated by Django 5.0.3 on 2025-05-03 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_post_p_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='p_url',
        ),
    ]
